--Q1

SELECT * FROM PARTIDA
    WHERE LOCAL = 'SANTOS';

--Q2

SELECT TIME1,TIME2, DATA, LOCAL FROM PARTIDA
    WHERE TIME1 = 'PALMEIRAS' OR TIME2 = 'PALMEIRAS';

--Q3

SELECT * FROM JOGADOR;

SELECT J.CPF, J.NOME, FLOOR((SYSDATE - J.DATA_NASC)/365) AS IDADE, T.NOME, T.ESTADO 
    FROM JOGADOR J JOIN TIME T ON J.TIME = T.NOME;

--Q4

--versão 1
SELECT J.CPF, J.NOME, J.DATA_NASC, T.NOME 
    FROM JOGADOR J, TIME T
    WHERE J.TIME = T.NOME AND T.ESTADO = 'SP';
    
--versão 2
SELECT J.CPF, J.NOME, J.DATA_NASC, T.NOME
    FROM JOGADOR J JOIN TIME T ON J.TIME = T.NOME
    WHERE T.ESTADO = 'SP';
    
--Q6

SELECT P.TIME1, P.TIME2, P.DATA, P.PLACAR, J.CLASSICO 
    FROM PARTIDA P JOIN JOGA J ON P.TIME1 = J.TIME1 AND P.TIME2 = J.TIME2
    WHERE P.LOCAL = 'SANTOS';

--Q7

--DUVIDA: O RETORNO ERA PRA SER LINHA A LINHA OU CONFRONTO ??

SELECT T.NOME, T.ESTADO 
    FROM JOGA J JOIN TIME T ON J.TIME1 = T.NOME OR J.TIME2 = T.NOME
    WHERE J.CLASSICO = 'S';

--Q8

SELECT U.TIME, U.COR_PRINCIPAL
    FROM UNIFORME U JOIN TIME T ON U.TIME = T.NOME
    WHERE   U.TIPO = 'TITULAR' AND
            T.TIPO = 'PROFISSIONAL' AND
            T.ESTADO = 'MG';

--Q9

SELECT DISTINCT P.TIME1, P.TIME2, P.DATA, P.PLACAR, P.LOCAL
    FROM PARTIDA P JOIN TIME T ON T.NOME = P.TIME1 OR T.NOME = P.TIME2
    WHERE T.ESTADO = 'SP';

--Q10

SELECT T.NOME, P.LOCAL
    FROM TIME T JOIN PARTIDA P ON T.NOME = P.TIME1 OR T.NOME = P.TIME2
    WHERE P.LOCAL <> 'SAO CARLOS' AND P.LOCAL <> 'BELO HORIZONTE';

SELECT T.NOME 
    FROM TIME T JOIN PARTIDA P ON T.NOME = P.TIME1 OR T.NOME = P.TIME2
    WHERE P.LOCAL = 'SAO CARLOS' OR P.LOCAL = 'BELO HORIZONTE';
    
SELECT T.NOME 
    FROM TIME T 
    WHERE T.NOME NOT IN 
    (SELECT T.NOME FROM TIME T 
        JOIN PARTIDA P ON T.NOME = P.TIME1 OR T.NOME = P.TIME2
        WHERE P.LOCAL = 'SAO CARLOS' OR P.LOCAL = 'BELO HORIZONTE');

SELECT * FROM JOGA;
SELECT * FROM JOGADOR;
SELECT * FROM TIME;
SELECT * FROM PARTIDA;
SELECT * FROM UNIFORME;